### PR TITLE
Merge dev to main

### PR DESCRIPTION
**Pull request by BAMF0**
We should be able to conclude version 0.1.0 now

### CODE REVIEW

**Review by simonengstrm — APPROVED** [review]
Looks good.

**Comment by BAMF0** [comment]
We should change the name of `dev` to `stable` so that it can be the default branch.

**Review by JonatanMentzer — CHANGES_REQUESTED** [review]
In tests/register_operation_tests.proptest-regressions there are unresolved merge conflicts at line 9 to 13. i don't know what is correct.

**Review by edvinsternvik — CHANGES_REQUESTED** [review]
1.
We should remove the following code (in src/lib.rs):
```

pub fn add(left: usize, right: usize) -> usize {
    left + right
}
#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn it_works() {
        let result = add(2, 2);
        assert_eq!(result, 4);
    }
}
```
as it is no longer needed.

2.
Fix the merge conflict in tests/register_operation_tests.proptest-regression

Otherwise it looks good.

**Review by JonatanMentzer — APPROVED** [review]
*Tumme upp*

**Review by edvinsternvik — APPROVED** [review]

**Pull request merged**
